# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 028c12e490531882a6ac1a871166327f8c0e73aef4043732489f0f49a3919ac6cb0a919e1342cb6ef9ab7cc3d367f00e106adbc462579a8957383a4f838927f0

test:
  secret_key_base: efb7eee4e15b4fe997c27d4aaa4a7cfcb19e8aee924994ea81092b0ceedec1c89a16cd4638651951ce5d2739d6aab0bb35c0ea342832028faef2f61c32dc78bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
